// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/gophkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemType int32

const (
	ItemType_ITEM_TYPE_UNSPECIFIED    ItemType = 0
	ItemType_ITEM_TYPE_LOGIN_PASSWORD ItemType = 1
	ItemType_ITEM_TYPE_TEXT           ItemType = 2
	ItemType_ITEM_TYPE_BINARY         ItemType = 3
	ItemType_ITEM_TYPE_BANK_CARD      ItemType = 4
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "ITEM_TYPE_UNSPECIFIED",
		1: "ITEM_TYPE_LOGIN_PASSWORD",
		2: "ITEM_TYPE_TEXT",
		3: "ITEM_TYPE_BINARY",
		4: "ITEM_TYPE_BANK_CARD",
	}
	ItemType_value = map[string]int32{
		"ITEM_TYPE_UNSPECIFIED":    0,
		"ITEM_TYPE_LOGIN_PASSWORD": 1,
		"ITEM_TYPE_TEXT":           2,
		"ITEM_TYPE_BINARY":         3,
		"ITEM_TYPE_BANK_CARD":      4,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_proto_gophkeeper_proto_enumTypes[0]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type RegisterRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login       *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RegisterRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RegisterRequest) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterRequest) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *RegisterRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type RegisterRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    *string
	Password *string
}

func (b0 RegisterRequest_builder) Build() *RegisterRequest {
	m0 := &RegisterRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Login = b.Login
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type RegisterResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId      *string                `protobuf:"bytes,1,opt,name=user_id,json=userId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		if x.xxx_hidden_UserId != nil {
			return *x.xxx_hidden_UserId
		}
		return ""
	}
	return ""
}

func (x *RegisterResponse) SetUserId(v string) {
	x.xxx_hidden_UserId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RegisterResponse) HasUserId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterResponse) ClearUserId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_UserId = nil
}

type RegisterResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId *string
}

func (b0 RegisterResponse_builder) Build() *RegisterResponse {
	m0 := &RegisterResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.UserId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_UserId = b.UserId
	}
	return m0
}

type LoginRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login       *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *LoginRequest) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *LoginRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *LoginRequest) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginRequest) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *LoginRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type LoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    *string
	Password *string
}

func (b0 LoginRequest_builder) Build() *LoginRequest {
	m0 := &LoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Login = b.Login
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type LoginResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       *string                `protobuf:"bytes,1,opt,name=token"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *LoginResponse) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *LoginResponse) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginResponse) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

type LoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token *string
}

func (b0 LoginResponse_builder) Build() *LoginResponse {
	m0 := &LoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Token = b.Token
	}
	return m0
}

type VaultItem struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id               *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Type             ItemType               `protobuf:"varint,2,opt,name=type,enum=gophkeeper.ItemType"`
	xxx_hidden_Title            *string                `protobuf:"bytes,3,opt,name=title"`
	xxx_hidden_Meta             *string                `protobuf:"bytes,4,opt,name=meta"`
	xxx_hidden_PayloadEncrypted []byte                 `protobuf:"bytes,5,opt,name=payload_encrypted,json=payloadEncrypted"`
	xxx_hidden_PayloadNonce     []byte                 `protobuf:"bytes,6,opt,name=payload_nonce,json=payloadNonce"`
	xxx_hidden_PayloadHash      *string                `protobuf:"bytes,7,opt,name=payload_hash,json=payloadHash"`
	xxx_hidden_Version          int64                  `protobuf:"varint,8,opt,name=version"`
	xxx_hidden_ClientUpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=client_updated_at,json=clientUpdatedAt"`
	xxx_hidden_CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt"`
	xxx_hidden_DeletedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=deleted_at,json=deletedAt"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *VaultItem) Reset() {
	*x = VaultItem{}
	mi := &file_proto_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultItem) ProtoMessage() {}

func (x *VaultItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VaultItem) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *VaultItem) GetType() ItemType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return ItemType_ITEM_TYPE_UNSPECIFIED
}

func (x *VaultItem) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *VaultItem) GetMeta() string {
	if x != nil {
		if x.xxx_hidden_Meta != nil {
			return *x.xxx_hidden_Meta
		}
		return ""
	}
	return ""
}

func (x *VaultItem) GetPayloadEncrypted() []byte {
	if x != nil {
		return x.xxx_hidden_PayloadEncrypted
	}
	return nil
}

func (x *VaultItem) GetPayloadNonce() []byte {
	if x != nil {
		return x.xxx_hidden_PayloadNonce
	}
	return nil
}

func (x *VaultItem) GetPayloadHash() string {
	if x != nil {
		if x.xxx_hidden_PayloadHash != nil {
			return *x.xxx_hidden_PayloadHash
		}
		return ""
	}
	return ""
}

func (x *VaultItem) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *VaultItem) GetClientUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ClientUpdatedAt
	}
	return nil
}

func (x *VaultItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *VaultItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *VaultItem) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DeletedAt
	}
	return nil
}

func (x *VaultItem) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 12)
}

func (x *VaultItem) SetType(v ItemType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 12)
}

func (x *VaultItem) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 12)
}

func (x *VaultItem) SetMeta(v string) {
	x.xxx_hidden_Meta = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 12)
}

func (x *VaultItem) SetPayloadEncrypted(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PayloadEncrypted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 12)
}

func (x *VaultItem) SetPayloadNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PayloadNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 12)
}

func (x *VaultItem) SetPayloadHash(v string) {
	x.xxx_hidden_PayloadHash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 12)
}

func (x *VaultItem) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 12)
}

func (x *VaultItem) SetClientUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ClientUpdatedAt = v
}

func (x *VaultItem) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *VaultItem) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *VaultItem) SetDeletedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_DeletedAt = v
}

func (x *VaultItem) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *VaultItem) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *VaultItem) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *VaultItem) HasMeta() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *VaultItem) HasPayloadEncrypted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *VaultItem) HasPayloadNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *VaultItem) HasPayloadHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *VaultItem) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *VaultItem) HasClientUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ClientUpdatedAt != nil
}

func (x *VaultItem) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *VaultItem) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *VaultItem) HasDeletedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DeletedAt != nil
}

func (x *VaultItem) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *VaultItem) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = ItemType_ITEM_TYPE_UNSPECIFIED
}

func (x *VaultItem) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Title = nil
}

func (x *VaultItem) ClearMeta() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Meta = nil
}

func (x *VaultItem) ClearPayloadEncrypted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_PayloadEncrypted = nil
}

func (x *VaultItem) ClearPayloadNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_PayloadNonce = nil
}

func (x *VaultItem) ClearPayloadHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_PayloadHash = nil
}

func (x *VaultItem) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Version = 0
}

func (x *VaultItem) ClearClientUpdatedAt() {
	x.xxx_hidden_ClientUpdatedAt = nil
}

func (x *VaultItem) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *VaultItem) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

func (x *VaultItem) ClearDeletedAt() {
	x.xxx_hidden_DeletedAt = nil
}

type VaultItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id               *string
	Type             *ItemType
	Title            *string
	Meta             *string
	PayloadEncrypted []byte
	PayloadNonce     []byte
	PayloadHash      *string
	Version          *int64
	ClientUpdatedAt  *timestamppb.Timestamp
	CreatedAt        *timestamppb.Timestamp
	UpdatedAt        *timestamppb.Timestamp
	DeletedAt        *timestamppb.Timestamp
}

func (b0 VaultItem_builder) Build() *VaultItem {
	m0 := &VaultItem{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 12)
		x.xxx_hidden_Id = b.Id
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 12)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 12)
		x.xxx_hidden_Title = b.Title
	}
	if b.Meta != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 12)
		x.xxx_hidden_Meta = b.Meta
	}
	if b.PayloadEncrypted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 12)
		x.xxx_hidden_PayloadEncrypted = b.PayloadEncrypted
	}
	if b.PayloadNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 12)
		x.xxx_hidden_PayloadNonce = b.PayloadNonce
	}
	if b.PayloadHash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 12)
		x.xxx_hidden_PayloadHash = b.PayloadHash
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 12)
		x.xxx_hidden_Version = *b.Version
	}
	x.xxx_hidden_ClientUpdatedAt = b.ClientUpdatedAt
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	x.xxx_hidden_DeletedAt = b.DeletedAt
	return m0
}

type CreateItemRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type             ItemType               `protobuf:"varint,1,opt,name=type,enum=gophkeeper.ItemType"`
	xxx_hidden_Title            *string                `protobuf:"bytes,2,opt,name=title"`
	xxx_hidden_Meta             *string                `protobuf:"bytes,3,opt,name=meta"`
	xxx_hidden_PayloadEncrypted []byte                 `protobuf:"bytes,4,opt,name=payload_encrypted,json=payloadEncrypted"`
	xxx_hidden_PayloadNonce     []byte                 `protobuf:"bytes,5,opt,name=payload_nonce,json=payloadNonce"`
	xxx_hidden_PayloadHash      *string                `protobuf:"bytes,6,opt,name=payload_hash,json=payloadHash"`
	xxx_hidden_ClientUpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=client_updated_at,json=clientUpdatedAt"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateItemRequest) GetType() ItemType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return ItemType_ITEM_TYPE_UNSPECIFIED
}

func (x *CreateItemRequest) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *CreateItemRequest) GetMeta() string {
	if x != nil {
		if x.xxx_hidden_Meta != nil {
			return *x.xxx_hidden_Meta
		}
		return ""
	}
	return ""
}

func (x *CreateItemRequest) GetPayloadEncrypted() []byte {
	if x != nil {
		return x.xxx_hidden_PayloadEncrypted
	}
	return nil
}

func (x *CreateItemRequest) GetPayloadNonce() []byte {
	if x != nil {
		return x.xxx_hidden_PayloadNonce
	}
	return nil
}

func (x *CreateItemRequest) GetPayloadHash() string {
	if x != nil {
		if x.xxx_hidden_PayloadHash != nil {
			return *x.xxx_hidden_PayloadHash
		}
		return ""
	}
	return ""
}

func (x *CreateItemRequest) GetClientUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ClientUpdatedAt
	}
	return nil
}

func (x *CreateItemRequest) SetType(v ItemType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *CreateItemRequest) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *CreateItemRequest) SetMeta(v string) {
	x.xxx_hidden_Meta = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *CreateItemRequest) SetPayloadEncrypted(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PayloadEncrypted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *CreateItemRequest) SetPayloadNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PayloadNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *CreateItemRequest) SetPayloadHash(v string) {
	x.xxx_hidden_PayloadHash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *CreateItemRequest) SetClientUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ClientUpdatedAt = v
}

func (x *CreateItemRequest) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateItemRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateItemRequest) HasMeta() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateItemRequest) HasPayloadEncrypted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CreateItemRequest) HasPayloadNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CreateItemRequest) HasPayloadHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *CreateItemRequest) HasClientUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ClientUpdatedAt != nil
}

func (x *CreateItemRequest) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = ItemType_ITEM_TYPE_UNSPECIFIED
}

func (x *CreateItemRequest) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Title = nil
}

func (x *CreateItemRequest) ClearMeta() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Meta = nil
}

func (x *CreateItemRequest) ClearPayloadEncrypted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_PayloadEncrypted = nil
}

func (x *CreateItemRequest) ClearPayloadNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_PayloadNonce = nil
}

func (x *CreateItemRequest) ClearPayloadHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_PayloadHash = nil
}

func (x *CreateItemRequest) ClearClientUpdatedAt() {
	x.xxx_hidden_ClientUpdatedAt = nil
}

type CreateItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type             *ItemType
	Title            *string
	Meta             *string
	PayloadEncrypted []byte
	PayloadNonce     []byte
	PayloadHash      *string
	ClientUpdatedAt  *timestamppb.Timestamp
}

func (b0 CreateItemRequest_builder) Build() *CreateItemRequest {
	m0 := &CreateItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Title = b.Title
	}
	if b.Meta != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Meta = b.Meta
	}
	if b.PayloadEncrypted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_PayloadEncrypted = b.PayloadEncrypted
	}
	if b.PayloadNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_PayloadNonce = b.PayloadNonce
	}
	if b.PayloadHash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_PayloadHash = b.PayloadHash
	}
	x.xxx_hidden_ClientUpdatedAt = b.ClientUpdatedAt
	return m0
}

type CreateItemResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Item *VaultItem             `protobuf:"bytes,1,opt,name=item"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateItemResponse) GetItem() *VaultItem {
	if x != nil {
		return x.xxx_hidden_Item
	}
	return nil
}

func (x *CreateItemResponse) SetItem(v *VaultItem) {
	x.xxx_hidden_Item = v
}

func (x *CreateItemResponse) HasItem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Item != nil
}

func (x *CreateItemResponse) ClearItem() {
	x.xxx_hidden_Item = nil
}

type CreateItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Item *VaultItem
}

func (b0 CreateItemResponse_builder) Build() *CreateItemResponse {
	m0 := &CreateItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Item = b.Item
	return m0
}

type GetItemRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetItemRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *GetItemRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetItemRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetItemRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type GetItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 GetItemRequest_builder) Build() *GetItemRequest {
	m0 := &GetItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type GetItemResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Item *VaultItem             `protobuf:"bytes,1,opt,name=item"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetItemResponse) GetItem() *VaultItem {
	if x != nil {
		return x.xxx_hidden_Item
	}
	return nil
}

func (x *GetItemResponse) SetItem(v *VaultItem) {
	x.xxx_hidden_Item = v
}

func (x *GetItemResponse) HasItem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Item != nil
}

func (x *GetItemResponse) ClearItem() {
	x.xxx_hidden_Item = nil
}

type GetItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Item *VaultItem
}

func (b0 GetItemResponse_builder) Build() *GetItemResponse {
	m0 := &GetItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Item = b.Item
	return m0
}

type ListItemsRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_IncludeDeleted bool                   `protobuf:"varint,1,opt,name=include_deleted,json=includeDeleted"`
	xxx_hidden_Limit          int32                  `protobuf:"varint,2,opt,name=limit"`
	xxx_hidden_Offset         int32                  `protobuf:"varint,3,opt,name=offset"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListItemsRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.xxx_hidden_IncludeDeleted
	}
	return false
}

func (x *ListItemsRequest) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListItemsRequest) GetOffset() int32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ListItemsRequest) SetIncludeDeleted(v bool) {
	x.xxx_hidden_IncludeDeleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ListItemsRequest) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ListItemsRequest) SetOffset(v int32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ListItemsRequest) HasIncludeDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListItemsRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListItemsRequest) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ListItemsRequest) ClearIncludeDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_IncludeDeleted = false
}

func (x *ListItemsRequest) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Limit = 0
}

func (x *ListItemsRequest) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Offset = 0
}

type ListItemsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	IncludeDeleted *bool
	Limit          *int32
	Offset         *int32
}

func (b0 ListItemsRequest_builder) Build() *ListItemsRequest {
	m0 := &ListItemsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.IncludeDeleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_IncludeDeleted = *b.IncludeDeleted
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Limit = *b.Limit
	}
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Offset = *b.Offset
	}
	return m0
}

type ListItemsResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*VaultItem          `protobuf:"bytes,1,rep,name=items"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListItemsResponse) GetItems() []*VaultItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *ListItemsResponse) SetItems(v []*VaultItem) {
	x.xxx_hidden_Items = &v
}

type ListItemsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*VaultItem
}

func (b0 ListItemsResponse_builder) Build() *ListItemsResponse {
	m0 := &ListItemsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

type UpdateItemRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id               *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Title            *string                `protobuf:"bytes,2,opt,name=title"`
	xxx_hidden_Meta             *string                `protobuf:"bytes,3,opt,name=meta"`
	xxx_hidden_PayloadEncrypted []byte                 `protobuf:"bytes,4,opt,name=payload_encrypted,json=payloadEncrypted"`
	xxx_hidden_PayloadNonce     []byte                 `protobuf:"bytes,5,opt,name=payload_nonce,json=payloadNonce"`
	xxx_hidden_PayloadHash      *string                `protobuf:"bytes,6,opt,name=payload_hash,json=payloadHash"`
	xxx_hidden_ClientUpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=client_updated_at,json=clientUpdatedAt"`
	xxx_hidden_Version          int64                  `protobuf:"varint,8,opt,name=version"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateItemRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *UpdateItemRequest) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *UpdateItemRequest) GetMeta() string {
	if x != nil {
		if x.xxx_hidden_Meta != nil {
			return *x.xxx_hidden_Meta
		}
		return ""
	}
	return ""
}

func (x *UpdateItemRequest) GetPayloadEncrypted() []byte {
	if x != nil {
		return x.xxx_hidden_PayloadEncrypted
	}
	return nil
}

func (x *UpdateItemRequest) GetPayloadNonce() []byte {
	if x != nil {
		return x.xxx_hidden_PayloadNonce
	}
	return nil
}

func (x *UpdateItemRequest) GetPayloadHash() string {
	if x != nil {
		if x.xxx_hidden_PayloadHash != nil {
			return *x.xxx_hidden_PayloadHash
		}
		return ""
	}
	return ""
}

func (x *UpdateItemRequest) GetClientUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ClientUpdatedAt
	}
	return nil
}

func (x *UpdateItemRequest) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *UpdateItemRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *UpdateItemRequest) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *UpdateItemRequest) SetMeta(v string) {
	x.xxx_hidden_Meta = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *UpdateItemRequest) SetPayloadEncrypted(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PayloadEncrypted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *UpdateItemRequest) SetPayloadNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PayloadNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *UpdateItemRequest) SetPayloadHash(v string) {
	x.xxx_hidden_PayloadHash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *UpdateItemRequest) SetClientUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ClientUpdatedAt = v
}

func (x *UpdateItemRequest) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *UpdateItemRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateItemRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateItemRequest) HasMeta() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UpdateItemRequest) HasPayloadEncrypted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UpdateItemRequest) HasPayloadNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *UpdateItemRequest) HasPayloadHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *UpdateItemRequest) HasClientUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ClientUpdatedAt != nil
}

func (x *UpdateItemRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *UpdateItemRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *UpdateItemRequest) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Title = nil
}

func (x *UpdateItemRequest) ClearMeta() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Meta = nil
}

func (x *UpdateItemRequest) ClearPayloadEncrypted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_PayloadEncrypted = nil
}

func (x *UpdateItemRequest) ClearPayloadNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_PayloadNonce = nil
}

func (x *UpdateItemRequest) ClearPayloadHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_PayloadHash = nil
}

func (x *UpdateItemRequest) ClearClientUpdatedAt() {
	x.xxx_hidden_ClientUpdatedAt = nil
}

func (x *UpdateItemRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Version = 0
}

type UpdateItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id               *string
	Title            *string
	Meta             *string
	PayloadEncrypted []byte
	PayloadNonce     []byte
	PayloadHash      *string
	ClientUpdatedAt  *timestamppb.Timestamp
	Version          *int64
}

func (b0 UpdateItemRequest_builder) Build() *UpdateItemRequest {
	m0 := &UpdateItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Id = b.Id
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Title = b.Title
	}
	if b.Meta != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Meta = b.Meta
	}
	if b.PayloadEncrypted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_PayloadEncrypted = b.PayloadEncrypted
	}
	if b.PayloadNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_PayloadNonce = b.PayloadNonce
	}
	if b.PayloadHash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_PayloadHash = b.PayloadHash
	}
	x.xxx_hidden_ClientUpdatedAt = b.ClientUpdatedAt
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type UpdateItemResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Item *VaultItem             `protobuf:"bytes,1,opt,name=item"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateItemResponse) Reset() {
	*x = UpdateItemResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemResponse) ProtoMessage() {}

func (x *UpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateItemResponse) GetItem() *VaultItem {
	if x != nil {
		return x.xxx_hidden_Item
	}
	return nil
}

func (x *UpdateItemResponse) SetItem(v *VaultItem) {
	x.xxx_hidden_Item = v
}

func (x *UpdateItemResponse) HasItem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Item != nil
}

func (x *UpdateItemResponse) ClearItem() {
	x.xxx_hidden_Item = nil
}

type UpdateItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Item *VaultItem
}

func (b0 UpdateItemResponse_builder) Build() *UpdateItemResponse {
	m0 := &UpdateItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Item = b.Item
	return m0
}

type DeleteItemRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteItemRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *DeleteItemRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteItemRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteItemRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type DeleteItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 DeleteItemRequest_builder) Build() *DeleteItemRequest {
	m0 := &DeleteItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type DeleteItemResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_DeletedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteItemResponse) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *DeleteItemResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DeletedAt
	}
	return nil
}

func (x *DeleteItemResponse) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DeleteItemResponse) SetDeletedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_DeletedAt = v
}

func (x *DeleteItemResponse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteItemResponse) HasDeletedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DeletedAt != nil
}

func (x *DeleteItemResponse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *DeleteItemResponse) ClearDeletedAt() {
	x.xxx_hidden_DeletedAt = nil
}

type DeleteItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        *string
	DeletedAt *timestamppb.Timestamp
}

func (b0 DeleteItemResponse_builder) Build() *DeleteItemResponse {
	m0 := &DeleteItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_DeletedAt = b.DeletedAt
	return m0
}

type SyncItemsRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LastSyncAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_sync_at,json=lastSyncAt"`
	xxx_hidden_IncludeDeleted bool                   `protobuf:"varint,2,opt,name=include_deleted,json=includeDeleted"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SyncItemsRequest) Reset() {
	*x = SyncItemsRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncItemsRequest) ProtoMessage() {}

func (x *SyncItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncItemsRequest) GetLastSyncAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastSyncAt
	}
	return nil
}

func (x *SyncItemsRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.xxx_hidden_IncludeDeleted
	}
	return false
}

func (x *SyncItemsRequest) SetLastSyncAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastSyncAt = v
}

func (x *SyncItemsRequest) SetIncludeDeleted(v bool) {
	x.xxx_hidden_IncludeDeleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *SyncItemsRequest) HasLastSyncAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastSyncAt != nil
}

func (x *SyncItemsRequest) HasIncludeDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SyncItemsRequest) ClearLastSyncAt() {
	x.xxx_hidden_LastSyncAt = nil
}

func (x *SyncItemsRequest) ClearIncludeDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_IncludeDeleted = false
}

type SyncItemsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LastSyncAt     *timestamppb.Timestamp
	IncludeDeleted *bool
}

func (b0 SyncItemsRequest_builder) Build() *SyncItemsRequest {
	m0 := &SyncItemsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LastSyncAt = b.LastSyncAt
	if b.IncludeDeleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_IncludeDeleted = *b.IncludeDeleted
	}
	return m0
}

type SyncItemsResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items      *[]*VaultItem          `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_ServerTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SyncItemsResponse) Reset() {
	*x = SyncItemsResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncItemsResponse) ProtoMessage() {}

func (x *SyncItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SyncItemsResponse) GetItems() []*VaultItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *SyncItemsResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ServerTime
	}
	return nil
}

func (x *SyncItemsResponse) SetItems(v []*VaultItem) {
	x.xxx_hidden_Items = &v
}

func (x *SyncItemsResponse) SetServerTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_ServerTime = v
}

func (x *SyncItemsResponse) HasServerTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ServerTime != nil
}

func (x *SyncItemsResponse) ClearServerTime() {
	x.xxx_hidden_ServerTime = nil
}

type SyncItemsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items      []*VaultItem
	ServerTime *timestamppb.Timestamp
}

func (b0 SyncItemsResponse_builder) Build() *SyncItemsResponse {
	m0 := &SyncItemsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_ServerTime = b.ServerTime
	return m0
}

var File_proto_gophkeeper_proto protoreflect.FileDescriptor

const file_proto_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x16proto/gophkeeper.proto\x12\n" +
	"gophkeeper\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"+\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xf7\x03\n" +
	"\tVaultItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.gophkeeper.ItemTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04meta\x18\x04 \x01(\tR\x04meta\x12+\n" +
	"\x11payload_encrypted\x18\x05 \x01(\fR\x10payloadEncrypted\x12#\n" +
	"\rpayload_nonce\x18\x06 \x01(\fR\fpayloadNonce\x12!\n" +
	"\fpayload_hash\x18\a \x01(\tR\vpayloadHash\x12\x18\n" +
	"\aversion\x18\b \x01(\x03R\aversion\x12F\n" +
	"\x11client_updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0fclientUpdatedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xa4\x02\n" +
	"\x11CreateItemRequest\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.gophkeeper.ItemTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04meta\x18\x03 \x01(\tR\x04meta\x12+\n" +
	"\x11payload_encrypted\x18\x04 \x01(\fR\x10payloadEncrypted\x12#\n" +
	"\rpayload_nonce\x18\x05 \x01(\fR\fpayloadNonce\x12!\n" +
	"\fpayload_hash\x18\x06 \x01(\tR\vpayloadHash\x12F\n" +
	"\x11client_updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0fclientUpdatedAt\"?\n" +
	"\x12CreateItemResponse\x12)\n" +
	"\x04item\x18\x01 \x01(\v2\x15.gophkeeper.VaultItemR\x04item\" \n" +
	"\x0eGetItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x0fGetItemResponse\x12)\n" +
	"\x04item\x18\x01 \x01(\v2\x15.gophkeeper.VaultItemR\x04item\"i\n" +
	"\x10ListItemsRequest\x12'\n" +
	"\x0finclude_deleted\x18\x01 \x01(\bR\x0eincludeDeleted\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"@\n" +
	"\x11ListItemsResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.gophkeeper.VaultItemR\x05items\"\xa4\x02\n" +
	"\x11UpdateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04meta\x18\x03 \x01(\tR\x04meta\x12+\n" +
	"\x11payload_encrypted\x18\x04 \x01(\fR\x10payloadEncrypted\x12#\n" +
	"\rpayload_nonce\x18\x05 \x01(\fR\fpayloadNonce\x12!\n" +
	"\fpayload_hash\x18\x06 \x01(\tR\vpayloadHash\x12F\n" +
	"\x11client_updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0fclientUpdatedAt\x12\x18\n" +
	"\aversion\x18\b \x01(\x03R\aversion\"?\n" +
	"\x12UpdateItemResponse\x12)\n" +
	"\x04item\x18\x01 \x01(\v2\x15.gophkeeper.VaultItemR\x04item\"#\n" +
	"\x11DeleteItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"_\n" +
	"\x12DeleteItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"y\n" +
	"\x10SyncItemsRequest\x12<\n" +
	"\flast_sync_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSyncAt\x12'\n" +
	"\x0finclude_deleted\x18\x02 \x01(\bR\x0eincludeDeleted\"}\n" +
	"\x11SyncItemsResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.gophkeeper.VaultItemR\x05items\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime*\x86\x01\n" +
	"\bItemType\x12\x19\n" +
	"\x15ITEM_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ITEM_TYPE_LOGIN_PASSWORD\x10\x01\x12\x12\n" +
	"\x0eITEM_TYPE_TEXT\x10\x02\x12\x14\n" +
	"\x10ITEM_TYPE_BINARY\x10\x03\x12\x17\n" +
	"\x13ITEM_TYPE_BANK_CARD\x10\x042\xd7\x04\n" +
	"\x11GophKeeperService\x12E\n" +
	"\bRegister\x12\x1b.gophkeeper.RegisterRequest\x1a\x1c.gophkeeper.RegisterResponse\x12<\n" +
	"\x05Login\x12\x18.gophkeeper.LoginRequest\x1a\x19.gophkeeper.LoginResponse\x12K\n" +
	"\n" +
	"CreateItem\x12\x1d.gophkeeper.CreateItemRequest\x1a\x1e.gophkeeper.CreateItemResponse\x12B\n" +
	"\aGetItem\x12\x1a.gophkeeper.GetItemRequest\x1a\x1b.gophkeeper.GetItemResponse\x12H\n" +
	"\tListItems\x12\x1c.gophkeeper.ListItemsRequest\x1a\x1d.gophkeeper.ListItemsResponse\x12K\n" +
	"\n" +
	"UpdateItem\x12\x1d.gophkeeper.UpdateItemRequest\x1a\x1e.gophkeeper.UpdateItemResponse\x12K\n" +
	"\n" +
	"DeleteItem\x12\x1d.gophkeeper.DeleteItemRequest\x1a\x1e.gophkeeper.DeleteItemResponse\x12H\n" +
	"\tSyncItems\x12\x1c.gophkeeper.SyncItemsRequest\x1a\x1d.gophkeeper.SyncItemsResponseB\x12Z\x10gophkeeper/protob\beditionsp\xe8\a"

var file_proto_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_gophkeeper_proto_goTypes = []any{
	(ItemType)(0),                 // 0: gophkeeper.ItemType
	(*RegisterRequest)(nil),       // 1: gophkeeper.RegisterRequest
	(*RegisterResponse)(nil),      // 2: gophkeeper.RegisterResponse
	(*LoginRequest)(nil),          // 3: gophkeeper.LoginRequest
	(*LoginResponse)(nil),         // 4: gophkeeper.LoginResponse
	(*VaultItem)(nil),             // 5: gophkeeper.VaultItem
	(*CreateItemRequest)(nil),     // 6: gophkeeper.CreateItemRequest
	(*CreateItemResponse)(nil),    // 7: gophkeeper.CreateItemResponse
	(*GetItemRequest)(nil),        // 8: gophkeeper.GetItemRequest
	(*GetItemResponse)(nil),       // 9: gophkeeper.GetItemResponse
	(*ListItemsRequest)(nil),      // 10: gophkeeper.ListItemsRequest
	(*ListItemsResponse)(nil),     // 11: gophkeeper.ListItemsResponse
	(*UpdateItemRequest)(nil),     // 12: gophkeeper.UpdateItemRequest
	(*UpdateItemResponse)(nil),    // 13: gophkeeper.UpdateItemResponse
	(*DeleteItemRequest)(nil),     // 14: gophkeeper.DeleteItemRequest
	(*DeleteItemResponse)(nil),    // 15: gophkeeper.DeleteItemResponse
	(*SyncItemsRequest)(nil),      // 16: gophkeeper.SyncItemsRequest
	(*SyncItemsResponse)(nil),     // 17: gophkeeper.SyncItemsResponse
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_proto_gophkeeper_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.VaultItem.type:type_name -> gophkeeper.ItemType
	18, // 1: gophkeeper.VaultItem.client_updated_at:type_name -> google.protobuf.Timestamp
	18, // 2: gophkeeper.VaultItem.created_at:type_name -> google.protobuf.Timestamp
	18, // 3: gophkeeper.VaultItem.updated_at:type_name -> google.protobuf.Timestamp
	18, // 4: gophkeeper.VaultItem.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 5: gophkeeper.CreateItemRequest.type:type_name -> gophkeeper.ItemType
	18, // 6: gophkeeper.CreateItemRequest.client_updated_at:type_name -> google.protobuf.Timestamp
	5,  // 7: gophkeeper.CreateItemResponse.item:type_name -> gophkeeper.VaultItem
	5,  // 8: gophkeeper.GetItemResponse.item:type_name -> gophkeeper.VaultItem
	5,  // 9: gophkeeper.ListItemsResponse.items:type_name -> gophkeeper.VaultItem
	18, // 10: gophkeeper.UpdateItemRequest.client_updated_at:type_name -> google.protobuf.Timestamp
	5,  // 11: gophkeeper.UpdateItemResponse.item:type_name -> gophkeeper.VaultItem
	18, // 12: gophkeeper.DeleteItemResponse.deleted_at:type_name -> google.protobuf.Timestamp
	18, // 13: gophkeeper.SyncItemsRequest.last_sync_at:type_name -> google.protobuf.Timestamp
	5,  // 14: gophkeeper.SyncItemsResponse.items:type_name -> gophkeeper.VaultItem
	18, // 15: gophkeeper.SyncItemsResponse.server_time:type_name -> google.protobuf.Timestamp
	1,  // 16: gophkeeper.GophKeeperService.Register:input_type -> gophkeeper.RegisterRequest
	3,  // 17: gophkeeper.GophKeeperService.Login:input_type -> gophkeeper.LoginRequest
	6,  // 18: gophkeeper.GophKeeperService.CreateItem:input_type -> gophkeeper.CreateItemRequest
	8,  // 19: gophkeeper.GophKeeperService.GetItem:input_type -> gophkeeper.GetItemRequest
	10, // 20: gophkeeper.GophKeeperService.ListItems:input_type -> gophkeeper.ListItemsRequest
	12, // 21: gophkeeper.GophKeeperService.UpdateItem:input_type -> gophkeeper.UpdateItemRequest
	14, // 22: gophkeeper.GophKeeperService.DeleteItem:input_type -> gophkeeper.DeleteItemRequest
	16, // 23: gophkeeper.GophKeeperService.SyncItems:input_type -> gophkeeper.SyncItemsRequest
	2,  // 24: gophkeeper.GophKeeperService.Register:output_type -> gophkeeper.RegisterResponse
	4,  // 25: gophkeeper.GophKeeperService.Login:output_type -> gophkeeper.LoginResponse
	7,  // 26: gophkeeper.GophKeeperService.CreateItem:output_type -> gophkeeper.CreateItemResponse
	9,  // 27: gophkeeper.GophKeeperService.GetItem:output_type -> gophkeeper.GetItemResponse
	11, // 28: gophkeeper.GophKeeperService.ListItems:output_type -> gophkeeper.ListItemsResponse
	13, // 29: gophkeeper.GophKeeperService.UpdateItem:output_type -> gophkeeper.UpdateItemResponse
	15, // 30: gophkeeper.GophKeeperService.DeleteItem:output_type -> gophkeeper.DeleteItemResponse
	17, // 31: gophkeeper.GophKeeperService.SyncItems:output_type -> gophkeeper.SyncItemsResponse
	24, // [24:32] is the sub-list for method output_type
	16, // [16:24] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_gophkeeper_proto_init() }
func file_proto_gophkeeper_proto_init() {
	if File_proto_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gophkeeper_proto_rawDesc), len(file_proto_gophkeeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_proto_gophkeeper_proto_depIdxs,
		EnumInfos:         file_proto_gophkeeper_proto_enumTypes,
		MessageInfos:      file_proto_gophkeeper_proto_msgTypes,
	}.Build()
	File_proto_gophkeeper_proto = out.File
	file_proto_gophkeeper_proto_goTypes = nil
	file_proto_gophkeeper_proto_depIdxs = nil
}
